feat: openPaymentPage that calls initiate,process together using Hype…
juspay/hyper-sdk-cordova pull request #8
Opened 2023-11-08 11:21 UTC by namitgoel

openPaymentPage that calls initiate,process together using HyperCheckoutLite openPaymentPage

2023-11-08 11:31 UTC, harshgarg18 requested changes

2023-11-08 11:31 UTC, harshgarg18 commented on www/hypersdk.js
> +        sharedCallback = callback;
why are we assigning callback to sharedCallback here? This is not required.

2023-11-08 11:31 UTC, harshgarg18 commented on src/android/HyperSDKPlugin.java
> +                HyperCheckoutLite.openPaymentPage(activity, params, new HyperPaymentsCallbackAdapter() {
We need to do this in a separate activity, as is done for the process call in the plugin.

CC: @Subhash703

2023-11-08 11:36 UTC, harshgarg18 commented
- [ ] @namitgoel - Can we get this tested before merge?

2023-11-09 12:51 UTC, Subhash703 commented on src/android/HyperSDKPlugin.java
> +            HyperCheckoutLite.openPaymentPage(activity, params, new HyperPaymentsCallbackAdapter() {
Why are we calling openPaymentPage in processWithActivity?

2023-11-14 09:16 UTC, harshgarg18 commented on src/android/build-extras.gradle
> +    def hyperSdkVersion = '2.1.20-rc.06'
Update SDK version here to 2.1.20-rc.10, or preferably, 2.1.20 once it is released by today/tmrw

2023-11-14 09:24 UTC, harshgarg18 requested changes
The code is not properly formatted as well.

2023-11-14 09:24 UTC, harshgarg18 commented on src/android/HyperSDKPlugin.java
> +                isHyperCheckoutLiteInteg = true;
We need to reset this flag after process_result, right?

2023-11-14 09:24 UTC, harshgarg18 commented on src/android/HyperSDKPlugin.java
> +                if (isPPMerchant(payloadParams)) {
is this condition really need? The function is called `openPaymentPage`!

2023-11-16 05:08 UTC, merged